/*
 * module function declaration for library bit header (autogenerated)
 */

#include "bit_module.h"

int bit_mod_init(ubx_node_info_t* ni)
{
  int ret;
  ret=bit_mod_init(ni);
  if(ret!=0)
    goto out;

out:
   return ret;
}

void bit_mod_cleanup(ubx_node_info_t* ni)
{
  bit_mod_cleanup(ni);
}

