/*
 * module function declaration for library sequence header (autogenerated)
 */

#include "sequence_module.h"

int sequence_mod_init(ubx_node_info_t* ni)
{
  int ret;
  ret=sequence_mod_init(ni);
  if(ret!=0)
    goto out;

out:
   return ret;
}

void sequence_mod_cleanup(ubx_node_info_t* ni)
{
  sequence_mod_cleanup(ni);
}

