/*
 * module function declaration for library toggle header (autogenerated)
 */

#include "toggle_module.h"

int toggle_mod_init(ubx_node_info_t* ni)
{
  int ret;
  ret=toggle_mod_init(ni);
  if(ret!=0)
    goto out;

out:
   return ret;
}

void toggle_mod_cleanup(ubx_node_info_t* ni)
{
  toggle_mod_cleanup(ni);
}

