/*
 * example_toggle microblx function block (autogenerated, don't edit)
 */

#include <ubx.h>

/* includes types and type metadata */


/* block meta information */
char example_toggle_meta[] =
        " { doc='',"
        "   real-time=true,"
        "}";

/* declaration of block configuration */
ubx_config_t example_toggle_config[] = {
        { NULL },
};

/* declaration port block ports */
ubx_port_t example_toggle_ports[] = {
        { .name="toggle", .out_type_name="int", .out_data_len=1, .in_type_name="int", .in_data_len=1, .doc="bit to toggle" },
        { NULL },
};

/* declare a struct port_cache */
struct example_toggle_port_cache {
        ubx_port_t* toggle;
};

/* declare a helper function to update the port cache this is necessary
 * because the port ptrs can change if ports are dynamically added or
 * removed. This function should hence be called after all
 * initialization is done, i.e. typically in 'start'
 */
static void update_port_cache(ubx_block_t *b, struct example_toggle_port_cache *pc)
{
        pc->toggle = ubx_port_get(b, "toggle");
}


/* for each port type, declare convenience functions to read/write from ports */
def_read_fun(read_toggle, int)

/* block operation forward declarations */
int example_toggle_init(ubx_block_t *b);
int example_toggle_start(ubx_block_t *b);
void example_toggle_stop(ubx_block_t *b);
void example_toggle_cleanup(ubx_block_t *b);
void example_toggle_step(ubx_block_t *b);


/* put everything together */
ubx_block_t example_toggle_block = {
        .name = "example_toggle",
        .type = BLOCK_TYPE_COMPUTATION,
        .meta_data = example_toggle_meta,
        .configs = example_toggle_config,
        .ports = example_toggle_ports,

        /* ops */
        .init = example_toggle_init,
        .start = example_toggle_start,
        .stop = example_toggle_stop,
        .cleanup = example_toggle_cleanup,
        .step = example_toggle_step,
};


/* example_toggle module init and cleanup functions */
int example_toggle_mod_init(ubx_node_info_t* ni)
{
        DBG(" ");
        int ret = -1;

        if(ubx_block_register(ni, &example_toggle_block) != 0)
                goto out;

        ret=0;
out:
        return ret;
}

void example_toggle_mod_cleanup(ubx_node_info_t *ni)
{
        DBG(" ");
        ubx_block_unregister(ni, "example_toggle");
}

