/*
 * example_bit microblx function block (autogenerated, don't edit)
 */

#include <ubx.h>

/* includes types and type metadata */


/* block meta information */
char example_bit_meta[] =
        " { doc='',"
        "   real-time=true,"
        "}";

/* declaration of block configuration */
ubx_config_t example_bit_config[] = {
        { .name="initial_value", .type_name = "int", .doc="" },
        { NULL },
};

/* declaration port block ports */
ubx_port_t example_bit_ports[] = {
        { .name="value", .out_type_name="int", .out_data_len=1, .in_type_name="int", .in_data_len=1, .doc="bit access port" },
        { NULL },
};

/* declare a struct port_cache */
struct example_bit_port_cache {
        ubx_port_t* value;
};

/* declare a helper function to update the port cache this is necessary
 * because the port ptrs can change if ports are dynamically added or
 * removed. This function should hence be called after all
 * initialization is done, i.e. typically in 'start'
 */
static void update_port_cache(ubx_block_t *b, struct example_bit_port_cache *pc)
{
        pc->value = ubx_port_get(b, "value");
}


/* for each port type, declare convenience functions to read/write from ports */
def_read_fun(read_value, int)

/* block operation forward declarations */
int example_bit_init(ubx_block_t *b);
int example_bit_start(ubx_block_t *b);
void example_bit_stop(ubx_block_t *b);
void example_bit_cleanup(ubx_block_t *b);


/* put everything together */
ubx_block_t example_bit_block = {
        .name = "example_bit",
        .type = BLOCK_TYPE_COMPUTATION,
        .meta_data = example_bit_meta,
        .configs = example_bit_config,
        .ports = example_bit_ports,

        /* ops */
        .init = example_bit_init,
        .start = example_bit_start,
        .stop = example_bit_stop,
        .cleanup = example_bit_cleanup,
};


/* example_bit module init and cleanup functions */
int example_bit_mod_init(ubx_node_info_t* ni)
{
        DBG(" ");
        int ret = -1;

        if(ubx_block_register(ni, &example_bit_block) != 0)
                goto out;

        ret=0;
out:
        return ret;
}

void example_bit_mod_cleanup(ubx_node_info_t *ni)
{
        DBG(" ");
        ubx_block_unregister(ni, "example_bit");
}

